home/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',home,name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('transaction/', include('transaction.urls')),
    path('', include('home.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

transaction/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('create_supplier',CreateSupplier.as_view(),name='create_supplier'),
    path('supplier_list',SupplierList.as_view(),name='supplier_list'),
    path('update_supplier/<str:pk>',UpdateSupplier.as_view(),name='update_supplier'),
    path('delete_supplier/<str:pk>',DeleteSupplier.as_view(),name='delete_supplier'),
    path('purchase',PurchaseView.as_view(),name= 'purchases'),
    path('select_supplier',SelectSupplierView.as_view(),name= 'select_supplier'),
    path('new_purchase/<str:pk>',PurchaseCreateView.as_view(),name= 'new_purchase'),
    path('purchase_delete/<str:pk>',PurchaseDeleteView.as_view(),name= 'purchase_delete'),
    path('purchase_bill/<str:billno>',PurchaseBillView.as_view(),name= 'purchase_bill')
]

transaction/models.py
from django.db import models
import uuid
from inventory.models import *

class Supplier(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name =  models.CharField(max_length=250)
    phone = models.CharField(max_length=250,unique=True)
    address = models.CharField(max_length=250)
    email = models.EmailField(max_length=254, unique=True)
    gstn = models.CharField(max_length=15, unique=True)
    is_deleted = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name
    
class PurchaseItem (models.Model):
    billno = models.ForeignKey("PurchaseBill", on_delete=models.CASCADE, related_name='purchaseitem')
    stock = models.ForeignKey(Stock , on_delete=models.CASCADE, related_name="purchaseitem")  
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)

    def __str__(self):
        return "Bill no: "+ str(self.billno.billno)+", Item = "+ self.stock.name

class PurchaseBill(models.Model):
    billno = models.UUIDField(primary_key =True,default=uuid.uuid4)
    time = models.DateTimeField(auto_now_add=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, related_name='purchasesupplier')

    def __str__(self):
        return "Bill no: " + str(self.billno)
    def get_total_price(self):
        purchaseitems = PurchaseItem.objects.filter(billno = self)
        total = 0 
        for item in purchaseitems :
            total += item.totalprice
        return total
    def get_items_list(self):
        return PurchaseItem.objects.filter(billno = self)
    
    
class PurchaseBillDetails(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete= models.CASCADE, related_name="purchasedetailsbillno")
    
    eway = models.CharField(max_length=50 , blank = True, null=True)
    veh = models.CharField(max_length=50,blank = True, null =True)
    destination = models.CharField(max_length=50, blank=True, null=True)
    po = models.CharField(max_length=50, blank=True, null=True)
    cgst = models.CharField(max_length=50, blank=True, null=True)
    igst = models.CharField(max_length=50, blank=True, null=True)
    cess = models.CharField(max_length=50, blank=True, null=True)
    tcs = models.CharField(max_length=50, blank=True, null=True)
    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return "Bill no: "+ str(self.billno.billno)
    
    
    

transaction/forms.py
from django import forms
from .models import *
from inventory.models import *
from django.forms import formset_factory

class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ('name','phone','address','email','gstn')


class SelectSupplierForm(forms.ModelForm):
    def __init__(self, *args, **kwarge):
        super().__init__(*args,**kwarge)
        self.fields['supplier'].queryset = Supplier.objects.filter(is_deleted  = False)
        self.fields['supplier'].widget.attrs.update({'class':'textinput form-control'})

    class Meta:
        model = PurchaseBill
        fields = ['supplier']

class PurchaseItemForm(forms.ModelForm):
    def __init__(self,*args,**kwarge):
        super().__init__(*args,**kwarge)
        self.fields['stock'].queryset = Stock.objects.filter(is_deleted = False)
        self.fields['stock'].widget.attrs.update({'class':'textinput form-control setprice stock','required':'true'})
        self.fields['quantity'].widget.attrs.update({'class':'textinput form-control setprice quantity','min':'1','required': 'true'})
        self.fields['perprice'].widget.attrs.update({'class':'textinput form-control setprice price','min':'1','required': 'true'})

    class Meta:
        model = PurchaseItem
        fields = ['stock','quantity','perprice']

PurchaseItemFormset = formset_factory(PurchaseItemForm, extra=1)


class PurchaseDetailsForm(forms.ModelForm):
    class Meta:
        model = PurchaseBillDetails
        fields = ('eway', 'veh', 'destination', 'po', 'cgst', 'igst', 'cess', 'tcs', 'total', )

transaction/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from.models import *
from .forms import *


class CreateSupplier(SuccessMessageMixin, generic.CreateView):
    model = Supplier
    form_class = SupplierForm
    success_message = 'Create Supplier Successfully..'
    success_url = '/transaction/supplier_list'
    template_name = 'supplier/create_supplier.html'


class SupplierList(generic.ListView):
    model = Supplier
    queryset = Supplier.objects.filter(is_deleted = False)
    template_name = 'supplier/suppliers_List.html'
    context_object_name = 'supplier'
    paginate_by = 10


class UpdateSupplier(SuccessMessageMixin, generic.CreateView):
    model = Supplier
    form_class = SupplierForm
    success_message = 'Update Supplier Successfully..'
    success_url = '/inventory/supplier-list'
    template_name = 'supplier/update_supplier.html'

class DeleteSupplier(generic.View):
    template_name = 'supplier/delete_supplier.html'
    success_message = 'Delete Successfully...'

    def get(self,request,pk):
        sup = get_object_or_404(Supplier,pk=pk)
        return render(request,self.template_name,{'sup':sup})
    def post(self,request,pk):
        sup = get_object_or_404(Supplier,pk=pk)
        sup.is_deleted = True
        sup.save()
        messages.success(request,self.success_message)
        return redirect('supplier_list')
    


class PurchaseView(generic.ListView):
    model = PurchaseBill
    template_name = 'purchase/purchase_list.html'
    context_object_name = 'bills'
    ordering = ['-time']
    paginate_by = 10


class SelectSupplierView(generic.View):
    form_class = SelectSupplierForm
    template_name = 'purchase/select_supplier.html'

    def get(self,request,*args,**kwargs):
        form = self.form_class
        return render(request,self.template_name,{'form':form})
    
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            supplierid = request.POST.get('supplier')
            supplier = get_object_or_404(Supplier,id=supplierid)
            return redirect('new_purchase',supplier.id)
        return render(request,self.template_name,{'form':form})
    
class PurchaseCreateView(generic.View):
    template_name = 'purchase/new_purchase.html'

    def get(self,request,pk):
        formset = PurchaseItemFormset(request.GET or None)
        supplierobj = get_object_or_404(Supplier, pk =pk)
        context ={
            'formset' : formset,
            'supplier' : supplierobj,
        }
        return render(request,self.template_name,context)
    
    def post(self,request,pk):
        formset = PurchaseItemFormset(request.POST)
        supplierobj = get_object_or_404(Supplier,pk=pk)
        if formset.is_valid():
                # save bill
                billobj = PurchaseBill(supplier=supplierobj)
                billobj.save()
                # save bill details
                billdetailsobj = PurchaseBillDetails(billno=billobj)
                billdetailsobj.save()
                for form in formset:
                    billitem = form.save(commit=False)
                    billitem.billno = billobj
                    stock = get_object_or_404(Stock,name=billitem.stock.name)
                    billitem.totalprice = billitem.perprice * billitem.quantity
                    stock.quantity += billitem.quantity
                    stock.save()
                    billitem.save()
                messages.success(request,"Purchased items have been registered successfully")
                return redirect('purchase_bill',billno=billobj.billno)
                # return redirect("/")
        formset = PurchaseItemFormset(request.GET or None)
        context = {
        'formset' : formset,
        'supplier' : supplierobj
    } 
        return render(request, self.template_name, context)



class PurchaseDeleteView(SuccessMessageMixin,generic.DeleteView):
    model = PurchaseBill
    template_name = 'purchase/purchase_delete.html'
    success_url = '/transactions/purchases'

    def delete(self,*args,**kwargs):
        self.object = self.get_object()
        items = PurchaseBill.objects.filter(billno = self.object.billno)
        for item in items:
            stock = get_object_or_404(Stock,name = item.stock.name)
            if stock.is_deleted == False:
                stock.quantity -= item.quantity
                stock.save()
        messages.success(self.request, "Purchase bill has been deleted successfully")
        return super(PurchaseDeleteView,self).delete(*args,**kwargs)


class PurchaseBillView(generic.View):
    model = PurchaseBill
    template_name = "bill/purchase_bill.html"
    bill_base = "bill/bill_base.html"
    form_class = PurchaseDetailsForm

    def get_bill_context(self, billno,form):
        bill = get_object_or_404(PurchaseBill, billno = billno)
        items = PurchaseItem.objects.filter(billno = billno)
        billdetails = get_object_or_404(PurchaseBillDetails , billno = billno)
        return{
            'bill' : bill,
            'item' : items,
            'billdetails' : billdetails,
            'bill_base' : self.bill_base,
            'form' : form
        }
    def get(self, request , billno):
        billdetailobj = get_object_or_404(PurchaseBillDetails, billno = billno)
        form = self.form_class(instance=billdetailobj)
        context = self.get_bill_context(billno,form)
        return render(request,self.template_name ,context)
    
    def post(self, request , billno):
        billdetailobj = get_object_or_404(PurchaseBillDetails, billno = billno)
        form = self.form_class(request.POST, instance=billdetailobj)

        if form.is_valaid():
            form.save()
            messages.success(request,'Bill Details has been modified successfully')
        else:
            messages.error(request,'There was an error updating the bill details. Please check the form.')

        context = self.get_bill_context(billno,form)
        return render(request, self.template_name, context)
        

    

transaction/templates/purchase/new_purchase.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  New Purchase
{% endblock title %}
{% block content %}
      <div class="row">
        <div class="col-md-12">
          <div class="container">

            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div>

              <br>

              <div class="panel panel-default">
                <div class="panel-heading panel-heading-text">Supplier Details</div>
                <div class="panel-body">

                  <div class="form-group">
                    <label for="id_name" class="panel-body-text">Supplier Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{supplier.name}}" disabled>
                  </div>

                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label for="id_phone" class="panel-body-text">Phone No:</label>
                      <input type="text" class="form-control textinput" id="id_phone" value="{{supplier.phone}}" disabled>
                    </div>
                    <div class="form-group col-md-6">
                      <label for="id_gstin" class="panel-body-text">GSTIN No:</label>
                      <input type="gstin" class="form-control textinput" id="id_gstin" value="{{supplier.gstn}}" disabled>
                    </div>
                  </div>

                </div>
              </div>

              <br>

              <form method="post" class="panel panel-default">
                {% csrf_token %}
                {{formset.management_form}}
                <div class="panel-heading panel-heading-text">Product Details</div>

                <div id="stockitem">
                  <div class="panel-body">
                    {% for form in formset %}
                    <div class="row form-row">
                      <div class="form-group col-md-6">
                        <label class="panel-body-text">Stock:</label>
                        {{form.stock}}
                      </div>
                      <div class="form-group col-md-2">
                        <label class="panel-body-text">Price per item:</label>
                        {{form.perprice}}
                      </div>
                      <div class="form-group col-md-2">
                        <label class="panel-body-text">Quantity:</label>
                        {{form.quantity}}
                      </div>
                      <div class="form-group col-md-1">
                        <label class="panel-body-text">Price:</label>
                        <input type="text" class="textinput form-control totalprice" value="1" disabled required>
                      </div>
                      <div class="form-group col-md-1">
                        <label class="panel-body-text" style="color: #000">.</label>
                        <button class="form-control btn btn-danger remove-form-row">-</button>
                      </div>
                    </div>
                    {% endfor %}
                    <div style="text-align: right;">
                      <a href="#" class="add-form-row">+ Add More</a>
                    </div>
                  </div>
                </div>


                <br>

                <div class="align-middle">
                  <button type="submit" class="btn btn-success">Add to Purchases</button>
                  <a href="#" class="btn btn-danger">Go Back</a>
                  <a href="#" class="btn btn-secondary">Cancel</a>
                </div>

              </form>

            </div>
        </div>
      </div>

  </main>
  <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
  <script type="text/javascript">
    // Creates custom alert object
    var custom_alert = new custom_alert();
    // Stores the total number of item forms
    var total = 1;

    // Updates element index for dynamically added form rows
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx;
        
        if ($(el).attr("for")) {
            $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        }
        if (el.id) {
            el.id = el.id.replace(id_regex, replacement);
        }
        if (el.name) {
            el.name = el.name.replace(id_regex, replacement);
        }
    }

    // Clones a form row to add a new one
    function cloneMore(selector, prefix) {
        var newElement = $(selector).clone(true);

        // Update input names and ids for the new element
        newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
            var name = $(this).attr('name');
            if (name) {
                name = name.replace('-' + (total - 1) + '-', '-' + total + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });

        // Update labels for the new element
        newElement.find('label').each(function() {
            var forValue = $(this).attr('for');
            if (forValue) {
                forValue = forValue.replace('-' + (total - 1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
            }
        });

        total++;
        $('#id_' + prefix + '-TOTAL_FORMS').val(total);
        $(selector).after(newElement);

        return false;
    }

    // Deletes a form row
    function deleteForm(prefix, btn) {
        if (total > 1) {
            btn.closest('.form-row').remove();

            var forms = $('.form-row');
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);

            // Update indices for remaining form rows
            for (var i = 0, formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).find(':input').each(function() {
                    updateElementIndex(this, prefix, i);
                });
            }

            total--;
        } else {
            custom_alert.render("Field cannot be deleted");
        }

        return false;
    }

    // Event listener to add a new form row
    $(document).on('click', '.add-form-row', function(e) {
        e.preventDefault();
        cloneMore('.form-row:last', 'form');
        return false;
    });

    // Event listener to remove a form row
    $(document).on('click', '.remove-form-row', function(e) {
        e.preventDefault();
        deleteForm('form', $(this));
        return false;
    });
    // Updates the total price by multiplying 'price per item' and 'quantity'
    $(document).on('change', '.setprice', function(e) {
        e.preventDefault();
        // Get the values
        var element = $(this);
        var quantity = element.parents('.form-row').find('.quantity').val();
        var perprice = element.parents('.form-row').find('.price').val();

        // Calculate the total
        var tprice = quantity * perprice;
        // Set the calculated total to the field
        element.parents('.form-row').find('.totalprice').val(tprice);
        return false;
    });
  </script>
{% endblock content %}

transaction/templates/purchase/select_supplier.html
{% extends "base.html" %}
{% block title %}
  Select Supplier
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
          <div class="container">
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div> 
              <br>
              
              <form method="post">
                {% csrf_token %}
                      <div class="form-group">
                        {{form}}
                      </div>
                  <br>
                  <div class="align-middle">
                      <button type="submit" class="btn btn-success">Next</button>
                      <a href="" class="btn btn-secondary">Cancel</a>
                  </div>
              </form>

        </div>
      </div>
      <br>

    </div>
{% endblock content %}